---
- name: Build and deploy AWX
  hosts: all
  gather_facts: false
  roles:
    - { role: check_vars }
    - { role: image_build, when: "dockerhub_base is not defined and build_local is not defined" }
    - { role: local_build, when: "dockerhub_base is not defined and build_local is defined" }
    - { role: openshift, when: "openshift_host is defined" }
    #- { role: local_docker, when: "openshift_host is not defined" }

